[project]
name = "todo-app"
version = "0.1.0"
description = "A simple command-line todo application"
readme = "README.md"
authors = [
    {name = "Muhammad Tamjeed Hussain"}
]
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
